# -*- coding: utf-8 -*-
"""Práctica Despliegue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ekQ8vCoa9LcaKF4UJQSKcavaPyMb3Ty
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = "modelo-minería-de-datos.pkl"
model_rf, labelencoder,variables = pickle.load(open(filename, "rb"))

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos
#!pip install streamlit pyngrok scikit-learn joblib
import streamlit as st

st.title("Predicción de lluvía con condiciones dadas")

Indoor_Temperature_C = st.slider("Indoor_Temperature_C", min_value=4.0, max_value=31.0, value=21.3)
Indoor_Humidity = st.slider("Indoor_Humidity", min_value=20, max_value=100, value=74)
Outdoor_Temperature_C = st.slider("Outdoor_Temperature_C", min_value=4.0, max_value=31.0, value=16.0)
Outdoor_Humidity = st.slider("Outdoor_Humidity", min_value=20, max_value=100, value=96)
Relative_Pressure_hpa = st.slider("Relative_Pressure_hpa", min_value=900.0, max_value=4000.0, value=1012.9)
Absolute_Pressure_hpa = st.slider("Absolute_Pressure_hpa", min_value=600.0, max_value=1000.0, value=826.6)
Wind_Speed_kmh = st.slider("Wind_Speed_kmh", min_value=0.0, max_value=40.0, value=0.0)
Gust_kmh = st.slider("Gust_kmh", min_value=0.0, max_value=40.0, value=1.1)
DewPoint_C = st.slider("DewPoint_C", min_value=4.0, max_value=31.0, value=15.4)
WindChill_C = st.slider("WindChill_C", min_value=4.0, max_value=31.0, value=16.0)
Wind_Direction = st.selectbox("Wind_Direction", ["N", "NE", "ENE", "NNE", "NNW",
                                                 "SSE", "NW", "E", "SE", "S", "SSW",
                                                 "SW", "W", "WNW", "WSW", "?"])

#Dataframe
datos = [[Indoor_Temperature_C,	Indoor_Humidity,	Outdoor_Temperature_C, Outdoor_Humidity,
          Relative_Pressure_hpa, Absolute_Pressure_hpa, Wind_Speed_kmh,	Gust_kmh	,DewPoint_C,
          WindChill_C, Wind_Direction]]
data = pd.DataFrame(datos, columns=["Indoor_Temperature_C","Indoor_Humidity","Outdoor_Temperature_C",
                                    "Outdoor_Humidity","Relative_Pressure_hpa","Absolute_Pressure_hpa",
                                    "Wind_Speed_kmh","Gust_kmh","DewPoint_C","WindChill_C","Wind_Direction"]) #Dataframe con los mismos nombres de variables

#Se realiza la preparación
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=["Wind_Direction"], drop_first=False, dtype=int)
data_preparada.head()

data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

data_preparada.info()

""# **Predicciones**""

#Hacemos la predicción con el Tree
Y_pred = model_rf.predict(data_preparada)
print(Y_pred)

data["Rain"]=Y_pred
data.head()

data
# -*- coding: utf-8 -*-
"""Práctica Despliegue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ekQ8vCoa9LcaKF4UJQSKcavaPyMb3Ty
"""
"""
#Cargamos librerías principales

import pandas as pd

#Cargamos el modelo
import pickle
filename = "modelo-minería-de-datos.pkl"
model_rf, labelencoder,variables = pickle.load(open(filename, "rb"))

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos
#!pip install streamlit pyngrok scikit-learn joblib
import streamlit as st

st.title("Predicción de lluvía con condiciones dadas")

Indoor_Temperature_C = st.slider("Indoor_Temperature_C", min_value=4.0, max_value=31.0, value=21.3)
Indoor_Humidity = st.slider("Indoor_Humidity", min_value=20, max_value=100, value=74)
Outdoor_Temperature_C = st.slider("Outdoor_Temperature_C", min_value=4.0, max_value=31.0, value=16.0)
Outdoor_Humidity = st.slider("Outdoor_Humidity", min_value=20, max_value=100, value=96)
Relative_Pressure_hpa = st.slider("Relative_Pressure_hpa", min_value=900.0, max_value=4000.0, value=1012.9)
Absolute_Pressure_hpa = st.slider("Absolute_Pressure_hpa", min_value=600.0, max_value=1000.0, value=826.6)
Wind_Speed_kmh = st.slider("Wind_Speed_kmh", min_value=0.0, max_value=40.0, value=0.0)
Gust_kmh = st.slider("Gust_kmh", min_value=0.0, max_value=40.0, value=1.1)
DewPoint_C = st.slider("DewPoint_C", min_value=4.0, max_value=31.0, value=15.4)
WindChill_C = st.slider("WindChill_C", min_value=4.0, max_value=31.0, value=16.0)
Wind_Direction = st.selectbox("Wind_Direction", ["N", "NE", "ENE", "NNE", "NNW",
                                                 "SSE", "NW", "E", "SE", "S", "SSW",
                                                 "SW", "W", "WNW", "WSW", "?"])

if st.button("Predecir"):

    # Dataframe
    datos = [[
        Indoor_Temperature_C,
        Indoor_Humidity,
        Outdoor_Temperature_C,
        Outdoor_Humidity,
        Relative_Pressure_hpa,
        Absolute_Pressure_hpa,
        Wind_Speed_kmh,
        Gust_kmh,
        DewPoint_C,
        WindChill_C,
        Wind_Direction
    ]]

    data = pd.DataFrame(
        datos,
        columns=[
            "Indoor_Temperature_C",
            "Indoor_Humidity",
            "Outdoor_Temperature_C",
            "Outdoor_Humidity",
            "Relative_Pressure_hpa",
            "Absolute_Pressure_hpa",
            "Wind_Speed_kmh",
            "Gust_kmh",
            "DewPoint_C",
            "WindChill_C",
            "Wind_Direction"
        ]
    )

    # Preparación
    data_preparada = pd.get_dummies(
        data,
        columns=["Wind_Direction"],
        drop_first=False,
        dtype=int
    )

    data_preparada = data_preparada.reindex(
        columns=variables,
        fill_value=0
    )

    # Predicción
    Y_pred = model_rf.predict(data_preparada)

    # Resultado
    resultado = "Lluvia" if Y_pred[0] == 1 else "No lluvia"

    st.success(f"Predicción: {resultado}")
"""
